name: build-pulsejet
on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push (branch)
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pulsejet:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pulsejet:${{ github.sha }}

      - name: Build & push (tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pulsejet:${{ github.ref_name }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pulsejet:${{ github.sha }}
